name: Deploy Vulnerable Machine Setup

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run setup script
      run: |
        chmod +x setup_vuln.sh
        ./setup_vuln.sh

    - name: Copy additional scripts
      run: |
        cp cleanup_vulnerable_machine.sh /opt/vulnerable/
        cp setup_vulnerable_machine.sh /opt/vulnerable/
