name: Deploy Vulnerable Machine Setup

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run setup script on AWS machine
      run: |
        scp -o StrictHostKeyChecking=no setup_vuln.sh ubuntu@3.26.219.49:/tmp/setup_vuln.sh
        ssh -o StrictHostKeyChecking=no ubuntu@3.26.219.49 'chmod +x /tmp/setup_vuln.sh && sudo /tmp/setup_vuln.sh'

    - name: Copy additional scripts
      run: |
        scp -o StrictHostKeyChecking=no cleanup_vulnerable_machine.sh ubuntu@3.26.219.49:/opt/vulnerable/
        scp -o StrictHostKeyChecking=no another_script.sh ubuntu@3.26.219.49:/opt/vulnerable/
